name: ci

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-linux:
    name: "Build and Test with Java ${{ matrix.java }} on Linux (Ubuntu)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - "11"
          - "17"
          - "21"
          - "25"
    env:
      JVM_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v6
      - uses: coursier/cache-action@v7
      - uses: coursier/setup-action@v2
        with:
          apps: mill
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Check formatting
        run:
          ./mill --no-server mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll __.sources
          # ./mill mill.scalalib.scalafmt.ScalafmtModule/checkFormatAll --sources buildSources
      # - name: Check scalafix
      #   run:
      #     ./mill --no-server __.fix --check
      - name: Compile
        run: ./mill --no-server __.compile
      - name: Test
        run: ./mill --no-server __.test
      - name: Test publishArtifacts
        run: ./mill --no-server show __.publishArtifacts

  test-windows:
    name: "Build and Test with Java ${{ matrix.java }} on Windows"
    runs-on: windows-latest
    needs:
      - test-linux
    strategy:
      matrix:
        java:
          - "25" # only test one JVM version on Windows for now
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows # x64-windows-static
      VCPKG_ROOT: "${{ github.workspace }}\\vcpkg"
      VCPKG_INSTALLED_DIR: "${{ github.workspace }}\\vcpkg\\installed"
      VCPKG_COMMIT_ID: "66c0373dc7fca549e5803087b9487edfe3aca0a1" # vcpkg 2026.01.16 Release
      JVM_VERSION: ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v6
      - uses: coursier/cache-action@v7
      - uses: coursier/setup-action@v2
        with:
          apps: mill
      - id: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgGitCommitId: "${{ env.VCPKG_COMMIT_ID }}"
          runVcpkgInstall: true
          doNotCache: false

      - name: Compile
        env:
          SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
          SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
        run: .\mill --no-server __.compile
      - name: Test
        env:
          SCALANATIVE_INCLUDE_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\include"
          SCALANATIVE_LIB_DIRS: "${{ env.VCPKG_INSTALLED_DIR }}\\${{ env.VCPKG_DEFAULT_TRIPLET }}\\lib"
        run: .\mill --no-server __.test

  publish-sonatype:
    if: github.repository == 'lolgab/scala-native-crypto' && contains(github.ref, 'refs/tags/')
    needs:
      - test-linux
      - test-windows
    runs-on: ubuntu-latest
    env:
      SONATYPE_PGP_PRIVATE_KEY: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      SONATYPE_PGP_PRIVATE_KEY_PASSWORD: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v5
      - uses: coursier/cache-action@v7
      - uses: coursier/setup-action@v2
        with:
          apps: mill
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libssl-dev

      - name: Publish to Maven Central
        run: |
          if [[ $(git tag --points-at HEAD) != '' ]]; then
            echo $SONATYPE_PGP_PRIVATE_KEY | base64 --decode > gpg_key
            gpg --import --no-tty --batch --yes gpg_key
            rm gpg_key
            ./mill mill.scalalib.SonatypeCentralPublishModule/publishAll \
              --username "$SONATYPE_USER" \
              --password "$SONATYPE_PASSWORD" \
              --gpgArgs "--passphrase=$SONATYPE_PGP_PRIVATE_KEY_PASSWORD,--no-tty,--pinentry-mode,loopback,--batch,--yes,-a,-b" \
              --publishArtifacts __.publishArtifacts \
              --readTimeout  36000 \
              --awaitTimeout 36000 \
              --connectTimeout 36000 \
              --shouldRelease true
          fi
